### PR TITLE
feat-routes-web-ui

### LINKED ISSUE #12: [FEATURE] Create routes for the web ui
**Is your feature request related to a problem? Please describe.**
Create three routes for the react web ui, 
**/**          base route for home-page component
**/signup**    route for sign-up page component
**/login**     route for log-in page component

**Describe the solution you'd like**
Use react router to add page routing to the app

### PR DESCRIPTION
**Pull request by MariaAngella**
## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #12  

## How Has This Been Tested?
Tests LocalRoutes in the ContentSwitch under the AppRoutes

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by amkayondo — CHANGES_REQUESTED** [review]
add more tests like one that checks if the route requested is not available

**Comment by MariaAngella** [comment]
Added the test to check if the route requested is not available

**Review by amkayondo — CHANGES_REQUESTED** [review]
bring this function on top of the ContentSwitch finction so as it can be accessible  
[src/web_ui/src/components/AppRoutes/index.js](https://github.com/BuildForSDG/farmrail/pull/27/files#diff-51ef43b83ecb3a80a025f44f9c1c11b0)

```
const NoMatch = () => (
    <div>
        <h2>Oops nothing here!!</h2>
        <Link to="/">Take me home</Link>
    </div>
)

```

**Comment by MariaAngella** [comment]
> bring this function on top of the ContentSwitch finction so as it can be accessible
> [src/web_ui/src/components/AppRoutes/index.js](https://github.com/BuildForSDG/farmrail/pull/27/files#diff-51ef43b83ecb3a80a025f44f9c1c11b0)
> 
> ```
> const NoMatch = () => (
>     <div>
>         <h2>Oops nothing here!!</h2>
>         <Link to="/">Take me home</Link>
>     </div>
> )
> ```

Done

**Review by amkayondo — APPROVED** [review]
Good improvement here

**Review by kmwamasali — APPROVED** [review]

**Pull request merged**
